// Экспорт всех контроллеров
export * from './userController';
export * from './studentController';
export * from './groupController';
export * from './attendanceController';
export * from './paymentController';
export * from './sectionController';
export * from './branchController';
export * from './trialRequestController';